#!/usr/bin/env ruby

require 'webrick'

APPLESCRIPT = <<-OSASCRIPT
osascript -e 'tell application "Safari"
    tell application "System Events"
        tell process "Safari"
            keystroke "l" using {command down}
        end tell
    end tell
end tell'
OSASCRIPT

HTML = DATA.read

class Blank < WEBrick::HTTPServlet::AbstractServlet
  def do_GET(request, response)
    case request.path
    when '/'
      response.body = HTML
    when '/cmdl'
      system APPLESCRIPT
      response.body = 'ok'
    end
  end
end

opts = {
  BindAddress: "127.0.0.1",
  Port: 4339,
  AccessLog: []
}

server = WEBrick::HTTPServer.new(opts)
server.mount('/', Blank)

%w(INT TERM).each do |sig|
  trap(sig) { server.shutdown }
end

server.start

__END__
<!doctype html>
<html>
  <head>
    <meta charset='utf-8'>
    <title>blank</title>
    <style type="text/css">
      *, *:before, *:after {
        box-sizing: border-box;
      }
      body {
        font-size: 100px;
        font-family: sans-serif;
        background: #ddd;
        text-align: center;
      }
      a {
        color: #ccc;
        text-decoration: none;
      }
    </style>
  </head>
  <body>
    <h1>
      <a href='/cmdl' id='cmd-l'>cmd+l</a>
    </h1>
    <script type="text/javascript">
      (function() {
        document.addEventListener('DOMContentLoaded', function() {
          var cmdl = document.getElementById('cmd-l');

          cmdl.onclick = function(e) {
            e.preventDefault();
            cmdL();
          };

          setTimeout(function() { cmdl.click() }, 1); // wait a millisec
        });

        function cmdL() {
          var req = new XMLHttpRequest();
          req.onload = function(e) { console.log('ok', req.responseText) };
          req.open('get', '/cmdl', true);
          req.send();
        }
      })();
    </script>
  </body>
</html>
