#!/usr/bin/env ruby

require 'webrick'

class Blank < WEBrick::HTTPServlet::AbstractServlet
  def do_GET(request, response)
    case request.path
    when '/'
      response.body = File.read('./index.html')
    when '/cmdl'
      `osascript cmd-l.applescript`
      response.body = 'ok'
    end
  end
end

opts = {
  BindAddress: "127.0.0.1",
  Port: 4339,
  AccessLog: []
}

server = WEBrick::HTTPServer.new(opts)
server.mount('/', Blank)

%w(INT TERM).each do |sig|
  trap(sig) { server.shutdown }
end

server.start

